#!/bin/ksh
#
# PROVIDE: gunicorn_charter
# REQUIRE: DAEMON
# KEYWORDS:
#
# Gunicorn service for Charter Meals

: ${gunicorn_charter_enable:=YES}

daemon_dir="/var/www/htdocs/www.chartermeals.com"
daemon_venv="${daemon_dir}/charter_env"
daemon="${daemon_venv}/bin/gunicorn"
pidfile="/var/run/gunicorn_charter.pid"

# Use --graceful-timeout to restart workers that take too long
daemon_flags="--daemon --pid ${pidfile} --chdir ${daemon_dir} --bind 127.0.0.1:5000 app:app --workers 6 --threads 4 --timeout 60 --graceful-timeout 30"

rc_bg=NO

command_user="www"

. /etc/rc.d/rc.subr

rc_cmd "$1"
